### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by geemanjs** [dmcg/okey-doke#10]
Hey, 

Thanks for creating / maintaining this project.

I was wandering if you could get the latest version pushed to maven central (last version appears to be `1.2.0`). Would save our teams some confusion on having to remember to import the bintray repository. 

Thanks,
James

**Comment by dmcg** [comment]
Don't know why I didn't get a notification for this, sorry. I'm going to have to do this now because of the whole bintray death thing, here goes

**Comment by dmcg** [comment]
1.3.3 published to Maven Central
