### ISSUE TITLE
JUnit 5 Support

### ISSUE THREAD

**Issue by jshiell** [dmcg/okey-doke#7]
JUnit 4 doesn't hurt me enough anymore. Hence, the following TL;DR gist, which creates an extension to allow use with JUnit 5. I might do a [tested]* pull-request on hackday, but Java makes me sad 😢 In the meantime, this is hopefully useful for anyone else with the same question.

https://gist.github.com/jshiell/f8f0c985733bf9a437e964f9d66dd66d

Usage:
```
@ExtendWith(OkeyDokeExtension::class)
class ATest {
    @Test
    fun `should pass a valid output`(approver: Approver) {
        approver.assertApproved("valid output")
    }
}
```

* it is actually tested, but Gists are a pain with multiple files so :welp:

**Comment by dmcg** [comment]
PR incorporated a while back
